### PR TITLE
External embedded palette changes

### PR DESCRIPTION
**Pull request by sonninnos**
- Fixed Deekay + Ptoing
- Synced Colodore
- Added ChristopherJam
- Removed Pepto (old PAL)
- Renamed and simplified core options by utilizing option key+values (only C64 for now)

Any idea why those Colodore colors were different than in the source? Where are the values taken from and was it intentional? It does not look any worse IMO. I also concluded that the old pepto with the gimped luma was useless.

Deekay and Ptoing were completely missing the last line (light gray) for some mystical reason.

### CODE REVIEW

**Comment by rsn8887** [comment]
The original colodore in the Vice standalone code relied was calculated based on the user-adjustable sliders in standalone vice. It was made with all sliders at 100, and then the user could adjust it themselves.

Retroarch vice doesn't have the colodore sliders. The recommended colodore palette by the maker himself doesn't have all sliders at 100 (which looks abysmal btw), but uses 50,100,50 instead. This is the palette I put in. Also see code comments:
```
# VIC-II palette based on http://www.colodore.com/
# note by rsn8887: This is the corrected palette that comes up on www.colodore.com with the default slider settings Brightness: 50, Contrast: 100, Saturation: 50.
```

**Comment by sonninnos** [comment]
Doh, I did not realize to look at the `data/C64/colodore.vpl` but only the `include/embedded/vic_colodore_vic_vpl.h`.

Could have put the values back, but you just merged it.

**Comment by rsn8887** [comment]
Thanks, I didn't see you changed colodore.h I only looked for .vpl.

I just fixed it :)
https://github.com/libretro/vice-libretro/commit/c947f6177cbaadddc5228ce232ab703ae7271917

**Comment by rsn8887** [comment]
It was my bad for only putting the commit in .vpl but not in .h

**Pull request merged**
