### PR TITLE
Fix SuperCPU + embedded data, Readme updates

### LINKED ISSUE #178: x64scpu does not work
I know that you are already fully aware about this but I still want to track it so I created this issue.

The x64scpu core does not compile. Since there are almost no `#if defined(__XSCPU64__)` in the code compared to the other emutypes, I guess that the work on supporting it has not really started yet.

I am really looking forward to being able to play Metal Dust in RetroArch on my Shield TV.
https://www.protovision.games/shop/product_info.php?products_id=133

### PR DESCRIPTION
**Pull request by sonninnos**
Finally I had another look at the SuperCPU and sure enough it was ridiculously close to the goal from the get-go, but I was simply too clueless back then.. oops.

retroarch_2020_05_27_17_41_05_925

Also added embedded kernal+chargen so that no data files are required for basic use.

JiffyDOS does not work with the built-in kernal, but it does work with a proper kernal placed in `system/vice/SCPU64`. The kernal needs to be set explicitly in `vicerc`, as in just renaming it to the default `scpu64` does not work (for now):
```
[SCPU64]
SCPU64Name="scpu-dos-2.04.bin"
```

`scpu-dos-2.04.bin` required increasing the default autostart delay from 3 to 4, and `scpu-dos-1.4.bin` required 5.

retroarch_2020_05_27_18_04_25_484

retroarch_2020_05_27_18_04_27_464

retroarch_2020_05_27_21_09_20_903

Closes #178

### CODE REVIEW

**Comment by rsn8887** [comment]
Holy smokes! Thank you!!! Merging.

**Comment by WindyWinston** [comment]
Nice one !

**Comment by WindyWinston** [comment]
A question. The SuperCPU rom that you've baked into Vice doesn't include the JiffyDOS rom (obviously for legal reasons). If we wan't to use the rom that does include JiffyDOS then we have to manually run it through `vicerc`, the rom being `scpu-dos-2.04.bin` ? Do we also have to include the JiffyDOS drive rom in the vicerc file ?

**Comment by sonninnos** [comment]
Nope, the core option adds the drive ROMs as usual. I'll make the kernal automatic later, so that no `vicerc` tinkering is needed.

**Comment by WindyWinston** [comment]
Awesome, I just wanted to confirm because i've had a few beers,

**Comment by sonninnos** [comment]
Cheers, likewise!

**Comment by WindyWinston** [comment]
My mind ended up wandering off to something else last night! I tried this this morning but can't find it! Is it a separate core because it's not showing in Retroarch ? Is it still having trouble compiling ?

**Comment by sonninnos** [comment]
Heh, great timing. There is no buildbot recipe yet, so you need to build it yourself. I can share the Windows build.

**Comment by WindyWinston** [comment]
Thanks !

**Comment by WindyWinston** [comment]
I tried that Super Mario 64 and it works great! Also benefits from your dual SID addition!

**Comment by sonninnos** [comment]
Aye, works nicely with zero slowdowns. And also with the up-button core option the experience is extremely close to the real thing.

**Comment by WindyWinston** [comment]
I'm still not seeing a `scpu` core in Retroarch. There's only a couple of games that actually use it but I thought i'd let you know.

**Comment by sonninnos** [comment]
I've already tried to put the ball rolling. No idea yet what is needed and when it is done.

**Comment by WindyWinston** [comment]
No rush, there's very very little content that can benefit from it anyway.

**Comment by rsn8887** [comment]
In libretro-super, an info file and recipes for each supported platform are needed.

What about this info file?

https://github.com/rsn8887/libretro-super/commit/eb8992b4a4295ce405f3114e65a38b98b6902a55

**Comment by rsn8887** [comment]
What about this recipe for Switch?

https://github.com/rsn8887/libretro-super/commit/8d08f166055b42fabb2560fd50a03b0941c26a8c

If it looks good, recipe lines have to be added for all the supported platforms.

**Comment by sonninnos** [comment]
Pretty much, but with slight changes:
```
display_name = "Commodore - C64 SuperCPU (VICE xscpu64)"
systemname = "SuperCPU"
database = "Commodore - C64 SuperCPU"
```

And the EMUTYPE should be "xscpu64", not "xscpu"

And also please add the CBM-II 5x0 too while at it.

**Comment by rsn8887** [comment]
A new commit for scpu and cbm5x0. So far only libnx.

https://github.com/rsn8887/libretro-super/commit/d854e0d59656a3550e7569ff70fef49167486a8e

If you think it is ok @sonninnos, I will add other platforms and then make PR to libretro-super. Of course, feel free to copy and make PR yourself.

**Comment by sonninnos** [comment]
Sweet, looking fine to me!

**Comment by rsn8887** [comment]
Ok I made a PR:
https://github.com/libretro/libretro-super/pull/1428/commits/4d04639b583ba6100692958ca5b0c3df45fc8196

**Comment by sonninnos** [comment]
Nice, buildbot is chugging away. Any idea why on the ps3 recipe the `{ENABLED}` var is `NO` on all others except CBM-II cores..?

PUAE has `NO` on some recipes too, like `cores-ios-arm64-generic`,  `cores-tvos-arm64-generic`, and `psl1ght`, and is that intentional too and does `NO` even matter?

**Pull request merged**
