### PR TITLE
implement up to five-players

### PR DESCRIPTION
**Pull request by rsn8887**
I added an option to select a multitap adapter, and added up to five players.

This should now make it possible to play multiplayer Shotgun or IK+ Gold, by setting the emulated multitap to "Protovision_CGA".

I would welcome some kind of code review. I am inexperienced with libretro UI and I am not sure this is the correct way to add new options.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @r-type, would you like to review if this works as per the author's request?

**Comment by rsn8887** [comment]
I think I already fixed it and --amended my original commit. 

I am feeling adventurous so ready to merge I'd say.

**Comment by rsn8887** [comment]
BTW: Thanks for the quick attention

**Comment by rsn8887** [comment]
Tested working playing three player bomb mania on Vita TV using emulated Protovision CGA adapter

**Pull request merged**
