### PR TITLE
UI Improvements, more customization (Rebased and conflicts solved, to use instead of PR #74)

### PR DESCRIPTION
**Pull request by rsn8887**
This is a version of PR #74 by @sonninnos with the merge conflicts resolved.

I applied a little clean up (whitespace etc.) too.

It seems to work great!

Sonninnos' new virtual keyboard is fabulous! 

@sonninnos maybe you can take a look and see if you agree with my fixes etc.?

Note I rebased your commits to make merging locally easier for me (see commits in this PR), and I fixed all the conflict I hope. It compiles and runs fine here.

There were a lot of merge conflicts, so probably needs some testing.

Summary
=======
This PR adds the following features:
- add drive sound emulation option
- add drive sound volume option
- add autostart warp option
- add keypad joystick control (keyrah etc.)
- fixes cursor key up acting as run/stop finally
- improves the virtual keyboard a lot, it is very easy to control with dpad or mouse now, and fits on a single page
- add automatic drive type adjustment for .d71 and .d81 content
- make virtual keyboard and other emulator functions more easily mappable to keyboard keys or gamepad buttons in core options
- allow `---` (blank) to be mapped to gamepad buttons in core options
- improve the status bar display (four joystick inputs displayed etc.)
- remove the obsolete and confusing `Vice Menu`
- allow more C64 keyboard keys to be mapped to gamepad inputs in core options
- allow mapping of C64 keys to left/right stick analog stick directions

### CODE REVIEW

**Comment by rsn8887** [comment]
This is amazing! It is working really well already.

**Comment by rsn8887** [comment]
Retrojoy setting is not needed after all, I just enabled @sonninnos' fix for the cursor keys permanently:
- In `Quickmenu->Controls: Whenever `User 1` is set to `Vice Joystick` or `Retropad`, then automatically prevent up/down/left/right/fire button presses on port 1 from causing C64 keypresses (they are joystick input only).
- If the user has Retropad keyboard bindings on `User 1`, which is the default on desktop installs, this causes those keys (for example cursor keys for directions, and X for fire) to function as joystick inputs as expected.
- If the user has Retropad keyboard bindings on `User 1` and wants to use the full C64 keyboard including all hotkeys and cursor keys etc, just go to `quickmenu->controls` and set Port 1 to `Disconnected` or `Vice Keyboard`

This is IMO the best combination of @sonninnos' fix for cursor keys and my efforts, so now finally vice will behave how all other cores with keyboards behave. And it gets rid of the confusing retro joy setting once and for all.

**Comment by rsn8887** [comment]
Currently works on OSX but crashes on loading core on Switch... needs a bit more work. I will try to find out what's going on.

**Comment by sonninnos** [comment]
Hmm, make spits at me:

`
vice/src/arch/libretro/archdep.c:83:7: error: conflicting types for 'getcwd'
   83 | char* getcwd( char* buf, size_t size )
      |       ^~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/fcntl.h:8,
                 from vice/src/arch/libretro/archdep.c:36:
C:/msys64/mingw64/x86_64-w64-mingw32/include/io.h:279:17: note: previous declaration of 'getcwd' was here
  279 |   char *__cdecl getcwd (char *, int) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
      |                 ^~~~~~
`

**Comment by rsn8887** [comment]
Yes I removed those defines in an effort to force all platforms to only use the system directory for everything. I put them back in just now.

**Comment by rsn8887** [comment]
I found the reason for crash on Switch. In libretro-core.c, line 521+522:
```
   snprintf(buf[0],sizeof(buf[0]),"RetroPad SELECT; %s|%s",NULL, keys);
   snprintf(buf[1],sizeof(buf[1]),"RetroPad START; %s|%s",NULL, keys);
```

This crashes on some platforms, because of the NULL (undefined). On OSX it writes "(null)" on Switch it crashes. I replaced `NULL` with `""`, no crash anymore on Switch.

I fixed it in force-push just right now.

I also just now put the archdep_mkdir back in. I thought that was the crash on Switch, but it wasn't :)

Two more things I changed in effort to find the crash:
- sound somewhere was /50/10 instead of /50 I don't understand why changing it?
- sound fragment somewhere was 0 instead of 1, and _very_small instead of _medium. To find the crash I changed those.

Did you change these for better sound quality? Shall I change these back to your values? Will these settings maybe be too slow for systems like Vita and Switch? Should I put an ifdef for those slower platforms?

**Comment by rsn8887** [comment]
Ok sorry for the three or four force pushes, they basically:
- fix line endings in libretro-core.c to have more readable diffs
- put the ifdef guard around chwdir again
- fix the crash on switch (sprintf with NULL pointer)
- re-instate the archdep_mkdir to create `vice` subfolder in system dir if it doesn't exists (works fine on osx and Switch, too)

I will make regular commits from now on.

**Comment by sonninnos** [comment]
> Did you change these for better sound quality? Shall I change these back to your values? Will these settings maybe be too slow for systems like Vita and Switch? Should I put an ifdef for those slower platforms?

I tried to tackle the obvious sound delay in resid compared to fastsid and a real c64. Difference was probably just placebo, but needs more testing. I used 8-bit guys delaytest.prg.

**Comment by rsn8887** [comment]
I think that’s how nuklear gui works. It redraws everything every frame. It is smooth on Switch, but slow on Vita. Still usable though.

**Comment by rsn8887** [comment]
I just invited you to become a collaborator on my repo. Then you can push commits etc. they will appear here, too.

**Comment by sonninnos** [comment]
> Concerning Resid: Ok just tell me if we should put your setting back and I will make an ifdef for Switch/Vita. Vita is already struggling with resid. The Switch doesn’t have any problems with the resid luckily. I think resid got faster again in later Vice versions, but in 3.0 it is quite slow for some reason.
Best to just ignore the change, since it did not make that much of a difference.

**Comment by rsn8887** [comment]
In my opinion this Pull Request is now ready to merge, what do you think @sonninnos ?

**Comment by sonninnos** [comment]
Not quite yet, since something is preventing the drive sound emulation from kicking in when it should and did..

**Comment by rsn8887** [comment]
I made the Autostart Warp an option, because it does work. The effect is a bit small but quite significant, when you wait for a big game to load. On Switch, with autostart warp on, it takes 1:24 seconds to load Space Taxi until cracker intro. With autostart warp off, it takes 1:54 seconds until cracker intro. I just timed it. The autostart warp is only in effect during initial load, until "run".

The drive sound is just not playing during the autowarp, because all sound is disabled during warp always. In Space Taxi, I verified it plays later when the game loads again after the cracker intro. Space Taxi is a good example, because it loads several times. The drive sound is disabled only during initial `load "*",8,1` until `run`, but then plays later when Space Taxi starts loading the title screen, so it all works as intended in all cases.

I think we can maybe merge now, what do you say? Did you find anything else that's wrong? I think it works very well on Switch now. I might have to get rid of that one merge commit, that might take me one more force push, and then merge maybe?

**Comment by sonninnos** [comment]
Oh ok, it does make some difference, but then again I was used to the standalone vice autowarp speed, heh. Making it an option is probably best.

Sounds fine to me.

**Comment by rsn8887** [comment]
Tested extensively and ready to merge @twinaphex ! Thank you!

**Comment by sonninnos** [comment]
Offtopic:
BTW thanks for the reminder, I just got through the Space Taxi morning shift on the first try and made it to the ping pong level without crashing. The gameplay is still very tight, and even though it should be enjoyed with a joystick, it is pretty enjoyable with a wireless pad too.

And on a side note I have to point out how awesome multiplayer madness Air Taxi delivers on the mighty Amiga.

**Pull request merged**
