### PR TITLE
resid-fp: Fix system-header includes from cpp

### PR DESCRIPTION
**Pull request by AnaLogiC76**
Any system-header may only be included from sysincludes.h, this still
was not done in some cpp-files.

### CODE REVIEW

**Comment by rsn8887** [comment]
Thanks, but this doesn't compile on linux still: 
```
gcc-7 -D__LIBRETRO__ -fPIC  -I./include -I./libretro/include -I./libretro-common/include -I./libretro -I./libretro/nukleargui -I./libretro/nukleargui/nuklear -I./libretro/nukleargui/retro -I./include/embedded -I./include/compat -I. -DHAVE_CONFIG_H -I./vice/src/sid -I./vice/src -I./vice/src/arch/libretro -I./vice/src/c64 -I./vice/src/c64dtv -I./vice/src/c64/cart -I./vice/src/core -I./vice/src/crtc -I./vice/src/diag -I./vice/src/drive -I./vice/src/drive/iec -I./vice/src/drive/iec/c64exp -I./vice/src/drive/ieee -I./vice/src/drive/tcbm -I./vice/src/imagecontents -I./vice/src/joyport -I./vice/src/lib/p64 -I./vice/src/monitor -I./vice/src/raster -I./vice/src/resid -I./vice/src/residfp -I./vice/src/residfp/builders/residfp-builder/residfp -I./vice/src/rtc -I./vice/src/samplerdrv -I./vice/src/socketdrv -I./vice/src/tape -I./vice/src/tapeport -I./vice/src/userport -I./vice/src/vdc -I./vice/src/vdrive -I./vice/src/vicii -I./vice/src/video -DGIT_VERSION=\"" d1eb8eb"\" -O3 -DNDEBUG -DWANT_ZLIB -D__X64__ -DCORE_NAME=\"x64\" -std=c99 -c libretro/retro_files.c -o libretro/retro_files.o
libretro/retro_files.c: In function 'file_exists':
libretro/retro_files.c:31:58: error: 'S_IFDIR' undeclared (first use in this function)
      (buf.st_mode & (S_IRUSR|S_IWUSR)) && !(buf.st_mode & S_IFDIR))
```

**Comment by AnaLogiC76** [comment]
I'm curious as the flag should be defined in stat.h, no matter what C-version is used.
The only thing changed is -std=c99 and vice-source wouldn't compile with an older C-version.
Does it work if you remove that setting?

**Comment by AnaLogiC76** [comment]
All google could find about that error was in combination with -std=c99, suggestions were the linux- or gcc-installation being broken or a issue in the specific gcc-version.
Whatever, I propose to remove the -std=c99 flags in the locations I added them to, I could amend that to this PR.

**Comment by AnaLogiC76** [comment]
Checks have now passed, I hope now any issues are gone.

**Comment by rsn8887** [comment]
Ok, merging! Thanks.

**Pull request merged**
