### PR TITLE
Re-add resid-fp (8fdfffb) with fixes for C++98

### PR DESCRIPTION
**Pull request by AnaLogiC76**
Remove #define HAVE_CXX11 because not all compilers support C++11 and
conformance to C++98 is required.
Add missing #define constexpr to the compatibility-layer.
Also it is very unsafe to include library-headers with those defines
present, so make sure they are all included before sidcxx11.h by moving
those includes to a common sysincludes.h.

### CODE REVIEW

**Comment by rsn8887** [comment]
@AnaLogiC76 this fails compiling on iOS still, I thought this was fixed?

http://paste.libretro.com/195616

**Comment by rsn8887** [comment]
I think this fails compiling on iOS still, @AnaLogiC76?
```
In file included from vice/src/residfp/builders/residfp-builder/residfp/resample/SincResampler.cpp:28:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:40:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:163:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:860:13: error: too many template arguments for class template 'auto_ptr'
            unique_ptr<_CharT, void(*)(void*)> __h(0, free);
            ^                  ~~~~~~~~~~~~~~~
./vice/src/residfp/sidcxx11.h:32:22: note: expanded from macro 'unique_ptr'
#  define unique_ptr auto_ptr
```

**Comment by AnaLogiC76** [comment]
Was supposed to be but one of the system-includes was overlooked, I'm rechecking them all again and create a new PR.

**Comment by rsn8887** [comment]
Ok thanks :)

**Comment by rsn8887** [comment]
Hmm linux arm platforms are also failing to build, but worked on 02-27:
```arm-linux-gnueabihf-gcc -mfpu=neon -mfloat-abi=hard -DARM -marm -DALIGN_DWORD -mstructure-size-boundary=32 -mthumb-interwork -falign-functions=16 -pipe -fstack-protector -D__LIBRETRO__ -fPIC  -I./include -I./libretro/include -I./libretro-common/include -I./libretro -I./libretro/nukleargui -I./libretro/nukleargui/nuklear -I./libretro/nukleargui/retro -I./include/embedded -I./include/compat -I. -DHAVE_CONFIG_H -I./vice/src/sid -I./vice/src -I./vice/src/arch/libretro -I./vice/src/c64 -I./vice/src/c64/cart -I./vice/src/c64dtv -I./vice/src/core -I./vice/src/crtc -I./vice/src/diag -I./vice/src/drive -I./vice/src/drive/iec -I./vice/src/drive/iec/c64exp -I./vice/src/drive/ieee -I./vice/src/drive/tcbm -I./vice/src/imagecontents -I./vice/src/joyport -I./vice/src/lib/p64 -I./vice/src/monitor -I./vice/src/platform -I./vice/src/raster -I./vice/src/resid -I./vice/src/residfp -I./vice/src/residfp/builders/residfp-builder/residfp -I./vice/src/rtc -I./vice/src/samplerdrv -I./vice/src/socketdrv -I./vice/src/tape -I./vice/src/tapeport -I./vice/src/userport -I./vice/src/vdc -I./vice/src/vdrive -I./vice/src/viciisc -I./vice/src/video -DGIT_VERSION=\"" c6fa65b"\" -O3 -DNDEBUG -DWANT_ZLIB -D__X64SC__  -DCORE_NAME=\"x64sc\" -std=c99 -c libretro/retro_files.c -o libretro/retro_files.o
arm-linux-gnueabihf-gcc -mfpu=neon -mfloat-abi=hard -DARM -marm -DALIGN_DWORD -mstructure-size-boundary=32 -mthumb-interwork -falign-functions=16 -pipe -fstack-protector -D__LIBRETRO__ -fPIC  -I./include -I./libretro/include -I./libretro-common/include -I./libretro -I./libretro/nukleargui -I./libretro/nukleargui/nuklear -I./libretro/nukleargui/retro -I./include/embedded -I./include/compat -I. -DHAVE_CONFIG_H -I./vice/src/sid -I./vice/src -I./vice/src/arch/libretro -I./vice/src/c64 -I./vice/src/c64/cart -I./vice/src/c64dtv -I./vice/src/core -I./vice/src/crtc -I./vice/src/diag -I./vice/src/drive -I./vice/src/drive/iec -I./vice/src/drive/iec/c64exp -I./vice/src/drive/ieee -I./vice/src/drive/tcbm -I./vice/src/imagecontents -I./vice/src/joyport -I./vice/src/lib/p64 -I./vice/src/monitor -I./vice/src/platform -I./vice/src/raster -I./vice/src/resid -I./vice/src/residfp -I./vice/src/residfp/builders/residfp-builder/residfp -I./vice/src/rtc -I./vice/src/samplerdrv -I./vice/src/socketdrv -I./vice/src/tape -I./vice/src/tapeport -I./vice/src/userport -I./vice/src/vdc -I./vice/src/vdrive -I./vice/src/viciisc -I./vice/src/video -DGIT_VERSION=\"" c6fa65b"\" -O3 -DNDEBUG -DWANT_ZLIB -D__X64SC__  -DCORE_NAME=\"x64sc\" -std=c99 -c libretro/retro_disk_control.c -o libretro/retro_disk_control.o
arm-linux-gnueabihf-gcc -mfpu=neon -mfloat-abi=hard -DARM -marm -DALIGN_DWORD -mstructure-size-boundary=32 -mthumb-interwork -falign-functions=16 -pipe -fstack-protector -D__LIBRETRO__ -fPIC  -I./include -I./libretro/include -I./libretro-common/include -I./libretro -I./libretro/nukleargui -I./libretro/nukleargui/nuklear -I./libretro/nukleargui/retro -I./include/embedded -I./include/compat -I. -DHAVE_CONFIG_H -I./vice/src/sid -I./vice/src -I./vice/src/arch/libretro -I./vice/src/c64 -I./vice/src/c64/cart -I./vice/src/c64dtv -I./vice/src/core -I./vice/src/crtc -I./vice/src/diag -I./vice/src/drive -I./vice/src/drive/iec -I./vice/src/drive/iec/c64exp -I./vice/src/drive/ieee -I./vice/src/drive/tcbm -I./vice/src/imagecontents -I./vice/src/joyport -I./vice/src/lib/p64 -I./vice/src/monitor -I./vice/src/platform -I./vice/src/raster -I./vice/src/resid -I./vice/src/residfp -I./vice/src/residfp/builders/residfp-builder/residfp -I./vice/src/rtc -I./vice/src/samplerdrv -I./vice/src/socketdrv -I./vice/src/tape -I./vice/src/tapeport -I./vice/src/userport -I./vice/src/vdc -I./vice/src/vdrive -I./vice/src/viciisc -I./vice/src/video -DGIT_VERSION=\"" c6fa65b"\" -O3 -DNDEBUG -DWANT_ZLIB -D__X64SC__  -DCORE_NAME=\"x64sc\" -std=c99 -c libretro/nukleargui/retro/SDL_gfxPrimitives.c -o libretro/nukleargui/retro/SDL_gfxPrimitives.o
arm-linux-gnueabihf-gcc -mfpu=neon -mfloat-abi=hard -DARM -marm -DALIGN_DWORD -mstructure-size-boundary=32 -mthumb-interwork -falign-functions=16 -pipe -fstack-protector -D__LIBRETRO__ -fPIC  -I./include -I./libretro/include -I./libretro-common/include -I./libretro -I./libretro/nukleargui -I./libretro/nukleargui/nuklear -I./libretro/nukleargui/retro -I./include/embedded -I./include/compat -I. -DHAVE_CONFIG_H -I./vice/src/sid -I./vice/src -I./vice/src/arch/libretro -I./vice/src/c64 -I./vice/src/c64/cart -I./vice/src/c64dtv -I./vice/src/core -I./vice/src/crtc -I./vice/src/diag -I./vice/src/drive -I./vice/src/drive/iec -I./vice/src/drive/iec/c64exp -I./vice/src/drive/ieee -I./vice/src/drive/tcbm -I./vice/src/imagecontents -I./vice/src/joyport -I./vice/src/lib/p64 -I./vice/src/monitor -I./vice/src/platform -I./vice/src/raster -I./vice/src/resid -I./vice/src/residfp -I./vice/src/residfp/builders/residfp-builder/residfp -I./vice/src/rtc -I./vice/src/samplerdrv -I./vice/src/socketdrv -I./vice/src/tape -I./vice/src/tapeport -I./vice/src/userport -I./vice/src/vdc -I./vice/src/vdrive -I./vice/src/viciisc -I./vice/src/video -DGIT_VERSION=\"" c6fa65b"\" -O3 -DNDEBUG -DWANT_ZLIB -D__X64SC__  -DCORE_NAME=\"x64sc\" -std=c99 -c libretro/nukleargui/retro/retro_surface.c -o libretro/nukleargui/retro/retro_surface.o
libretro/retro_files.c: In function 'file_exists':
libretro/retro_files.c:31:59: error: 'S_IFDIR' undeclared (first use in this function)
      (buf.st_mode & (S_IRUSR|S_IWUSR)) && !(buf.st_mode & S_IFDIR))
                                                           ^
```
http://paste.libretro.com/195665

**Comment by rsn8887** [comment]
Have these resid-fp additions ever passed Travis checks for compilation on Linux? I didn't merge the original PRs.

**Comment by rsn8887** [comment]
https://travis-ci.org/libretro/vice-libretro/jobs/648392533?utm_medium=notification&utm_source=github_status

**Pull request merged**
