### PR TITLE
More options and more customization

### PR DESCRIPTION
**Pull request by sonninnos**
Also new virtual keyboard fitted in one page

### CODE REVIEW

**Comment by rsn8887** [comment]
This is cool IMO but needs to be rebased and conflicts solved.

**Comment by rsn8887** [comment]
I solved all the merge conflicts on my master branch here.

**Comment by rsn8887** [comment]
I urge all work to continue on https://github.com/libretro/vice-libretro/pull/76 I made it work and resolved all conflicts. It is working VERY well already, just a bit more testing.

**Comment by sonninnos** [comment]
Heh, the planets are aligning & thanks man!

I'm new to this, so I try to keep up and figure out how stuff n tings work.

**Pull request closed without merging**
