### PR TITLE
Add support for PET as a libretro core

### PR DESCRIPTION
**Pull request by raphkoster**
I added the Makefile for xpet and made all the various code changes to support the additional target.

### CODE REVIEW

**Comment by rsn8887** [comment]
Awesome! It will be cool to have a PET core.

I would love to test, what is the command to compile the PET core? So far I have just used the `make platform=osx` command, but it only builds the C64 core.

@sonninnos and I have been working the last few days on PR #76 and it will be ready to merge in less than a day I think. PR #76 should definitely be merged first because we have tested it extensively, and already worked hard to fix all the conflicts there. This PR would introduce additional conflicts there.

After merging PR #76, then the conflicts of this PR will have to be resolved. To aid in that effort, it would be great if no unnecessary diffs are introduced here. A few things I am seeing that will probably need addressing:
- There are a ton of line break changes that need to be fixed. They show up here on GitHub in the diffs as a trivial removal and reinsertion of the exact same code. 
- There are MANY changes in that Bison monitor code, what is going on there? Are these changes necessary for the PET functionality?

I can do these things, too, if you don't have time, but it would help me a lot to at least know about the reason for all those changes to the monitor code.

Thank you very much for the contribution! This has been an amazing week for the vice core after literally a year of basically zero progress!

**Comment by sonninnos** [comment]
> I would love to test, what is the command to compile the PET core? So far I have just used the `make platform=osx` command, but it only builds the C64 core.

make -f Makefile.libretro EMUTYPE=xpet

**Comment by raphkoster** [comment]
Thanks for looking at this!

I just reverted mon_parse.c, I didn't mean to include it.

Sorry about the line breaks; I did this all on my Pi just for fun a couple of weeks ago, and wasn't too careful. Then I thought huh, maybe I should contribute it back. I would welcome any help on fixing the line breaks, as I am definitely short on time these days.

**Comment by raphkoster** [comment]
I resolved the two conflicts, they were tiny, just some includes and a two line change in the controller code.

**Comment by rsn8887** [comment]
Perfect. Can you rebase on top of upstream master and force push to your branch, to get rid of the mon_parce.c stuff completely and to get rid of that last merge commit?

**Comment by rsn8887** [comment]
Don't merge, there is an updated rebased version PR #83

**Comment by raphkoster** [comment]
This PR was been rebased and is now PR 83.

**Pull request closed without merging**
