### PR TITLE
Add core-option to set sound output samplerate

### PR DESCRIPTION
**Pull request by AnaLogiC76**
While the hardcoded setting for 44100 is ok, there's now an option for slightly
higher quality or slightly higher performance.

### CODE REVIEW

**Comment by sonninnos** [comment]
A simple oneliner would be cleaner, but does not matter really:
`int rate=atoi(var.value);`

But are the lowest sound destroying options "8000" and "11025" really necessary? Do they give actual performance benefit in any scenario?

**Comment by AnaLogiC76** [comment]
I think the difference on modern machines is minimal, I've set 96000 for a while and couldn't see CPU use increase at all, so that would probably only be relevant for old mobile devices, like Android 4.4.
I added 8000 mostly to see if that still works fine.
VICE uses 22050 as default for Android builds if that helps.

**Comment by rsn8887** [comment]
Thanks!

**Comment by MajorWilly** [comment]
Is 96000 just a placebo setting ? In the Vice docs it only ranges from 8000-48000. I am using Android 4.4 but don't notice any performance changes at all. Maybe it needs rewording :smile:

**Comment by AnaLogiC76** [comment]
It's not placebo, while VICE only offers preset values up to 48000 you can also set a custom value like 96000 there as long as your soundhardware supports it.
Please also note that Retroarch controls the soundhardware while vice-libretro renders the sounddata, as Retroarch by default is set to 48000 change that to 96000 (in Setings => Audio => Output Rate) to actually get that out of your soundhardware.
Even then the difference will be hardly audible, as previously vice-libretro used a fixed soundrate of 44100 which is not bad at all.
If you do not notice a performance difference, that's great - please also note that a restart of the core is required for a change to samplerate to take effect. You could test with 8000 as this is definitely audible when applied.

**Comment by MajorWilly** [comment]
Thanks for the explanation. You can definitely hear the difference with 8000 but I doubt anyone would want it to sound like that when the default has the same performance. Maybe a Raspberry Pi Zero might benefit from the lower qualities though so it's good to have the option,

**Comment by sonninnos** [comment]
Well, if even 22050 does not help with the used machine then maybe better be without sound at all, because lower than that sounds awful. Though there is no option for not generating sound, since I guess FastSID is fast enough. I vote for removing those lowest of the low options, because less is more.

But sure, with synthesizer sound chips there can be a benefit of sampling as high as possible when generating even if the frontend resamples it back. Like supersampling for sound.

**Comment by AnaLogiC76** [comment]
I agree that for really low performance FastSID probably is goot enough, and while the argument having 8000 for testing purposes was that it makes an audible difference while you can still hear if sound generation works properly, I think 22050 should suffice for that with reasonable audio equipment.
Also there could be a point in removing 44100 as well, because Retroarch defaults to 48000 and maybe we should too, for less aliasing effects?
Also using atol instead of the switch-style would still allow any value in the config while keeping options in the UI to a minimum - I used switch-style because I've seen it being done that way for other options.
Just tell me the way to go and I'll make the way happen.

**Comment by sonninnos** [comment]
Let's keep 44100, because there at least sometimes existed sound cards which do that natively, and with 48000 produce a terrible ringing effect. Then again it may not even matter since the frontend resamples it anyway.

Sure would be nice if the frontend's rate could be sensed in the core, but I didn't find anything helpful in `libretro.h` about that.

**Comment by AnaLogiC76** [comment]
Just pushed commit with LQ options removed, default 48000 and updated labels.
Also now just using atoi for parsing as I found RA will replace any unlisted value with the default anyway.

Now how do I get the additional commit to show up in this PR?

My first plan actually was to use the samplerate as specified in RA settings, but I didn't find any API to get this setting either. If they ever provide that value I think we would no longer need that option here.
Actually it should be possible to switch samplerate at runtime using RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO - however this notice in the comments in libretro.h put me off doing that:
"Calling this can require a full reinitialization of video/audio drivers in the frontend"
Sounds like possible complications and I don't think thats worth it.

**Comment by rsn8887** [comment]
Thanks, can you make another PR with your changes, since this one is closed?

**Comment by sonninnos** [comment]
Switching PAL/NTSC already does that AV_INFO update, and if it is made so that it only fires up when the value actually changes, which is not that often, then I don't see a problem with it.

**Comment by AnaLogiC76** [comment]
I've now added runtime updating as second commit to PR #170, renamed title to WIP until I have verified there are no audible artefacts when switching.

**Pull request merged**
