### PR TITLE
New VKBD layout

### PR DESCRIPTION
**Pull request by sonninnos**
More faithful keyboard layout with also Datasette controls.

retroarch_2019_09_02_23_40_01_639

### CODE REVIEW

**Comment by sonninnos** [comment]
Please don't merge yet. Let's have a vote and/or ponder which is most usable:
retroarch_2019_09_03_01_30_03_346

or

retroarch_2019_09_03_01_36_12_114

**Comment by rsn8887** [comment]
I feel like the best layout might be the last one, but with the four F keys moved up three rows, on the top right, and special keys rst joy moved to a column to the right of of Dfw Dpl Drs.

Then all special keys are together, the f keys are to the right of 0, p, pnd, / with =, ret, crs> below F7.

**Comment by sonninnos** [comment]
retroarch_2019_09_03_03_43_15_422

Like so?

Not bad, but maybe some other discerning color for the Datasette buttons are needed.

**Comment by rsn8887** [comment]
Yeah at the moment that is my favorite but it is your decision really. All of them are fine with me :)

**Comment by sonninnos** [comment]
retroarch_2019_09_03_05_24_04_083

Starting to make sense. I'll push it so it can be tested in practice.

**Comment by MajorWilly** [comment]
This looks great. Is there any chance you could make the letters and numbers on the Amiga P-UAE keyboard a little bit bigger as it's quite hard to see on a small screen ? No worries if you can't.

**Comment by rsn8887** [comment]
I wonder if it will look even better if the bottom left nine special keys are moved to the bottom right? The  all the colorful stuff is on the right.

**Comment by sonninnos** [comment]
> This looks great. Is there any chance you could make the letters and numbers on the Amiga P-UAE keyboard a little bit bigger as it's quite hard to see on a small screen ? No worries if you can't.

I'll look into it some more, but so far I've only found a way to have them too small or too big. 


> I wonder if it will look even better if the bottom left nine special keys are moved to the bottom right? The all the colorful stuff is on the right.

We shall find out soonish.

**Comment by sonninnos** [comment]
retroarch_2019_09_03_16_10_25_946

Feels pretty solid now, and it almost went full circle back to the starting point, heh. Too bad the the "," and "." don't match with ":" and ";" anymore, but who cares.

Vkb button changed to Ttf as in "Toggle turbo fire".

**Comment by rsn8887** [comment]
Amazing, it looks perfect! Ready to merge?

**Comment by sonninnos** [comment]
Now I think it is ready!

**Comment by rsn8887** [comment]
Merged :)

**Pull request merged**
