### PR TITLE
Statusbar pimpin'

### PR DESCRIPTION
**Pull request by sonninnos**
More appealing joyport information.

### CODE REVIEW

**Comment by sonninnos** [comment]
Tried to amend but apparently botched it up.

**Comment by sonninnos** [comment]
Eeh.. wth

**Comment by rsn8887** [comment]
Can you rebase and squash all the commits here into a single “improve statusbar” commit? Thanks!

**Comment by sonninnos** [comment]
I'd like to but not quite sure how, I did some squashing but should I close this?

**Comment by rsn8887** [comment]
Perfect thanks!

**Pull request merged**
