### PR TITLE
New SID-engines: resid-33, resid-fp

### PR DESCRIPTION
**Pull request by AnaLogiC76**
As it may not be obvious why having additional variants of the resid-engine may be useful, let me explain the current situation as good as I could find out. It's all about the filters. Sorry for the long read in advance.

Resid as currently implemented in both VICE trunk and vice-libretro uses the filter-implementation of VICE 2.4, and that one only has emulation for the 6581-filters. This emulation is used for the 8580 too and this works surprisingly well, but it's not a proper emulation - and as a side-effect there is no way to configure filter-parameters for the 8580. It is said filter-components vary less for 8580 than they did for the 6581, but they do vary and the Resid 8580 doesn't sound like the 8580 in both my C64C and my C128D.
Still, resid (which I prefer to name resid-24) has been working fine for years and should stay as default for the time being.

Things should get better as work was underway to implement proper emulation of the 8580 filters, this is what I name resid-33 as the latest version was delivered in VICE 3.3 release. Unfortunately while most tunes sound fine, some caused very annoying clipping in the filters. After months VICE team decided to declare this filter-implementation "experimental" and revert to the implementation from VICE 2.4.
In September 2019 it was found that changing one value in the filter-parameters can bring the new filter-implementation in a working state - this was implemented in libsidplay-fp and proposed to be merged into VICE trunk aswell, with a slightly different value. That didn't happen and as the change in libsidplayfp has been out for several months I decided to go with their values.

Half an hour ago I found that VICE team actually merged the change on January 3rd. They used the value proposed in September, different from the one in libsidplayfp.
That's annoying. I need some input here, what values should I go with for vice-libretro?

While doing my investigation I found that residfp in sidplayfp was mentioned as an alternative implementation that maybe sounds better than resid and it's still being maintained. A long time ago residfp was in VICE, was abandoned by its author and removed from VICE, then picked up by Leandro "drfiemost" Nini for maintainance, I've found he also contributes patches to VICE up to this day.
And still it sounds slightly different to resid-33, and that's why it is in here as resid-fp.
The old residfp-source in VICE turned out to be unusable, so I did the integration from scratch.

I've had this in production use for a while but declared it as [wip] as there are different ways to integrate things, I plan to post some more details about that in a comment and I'm looking forward to the feedback.

If someone wants to try this out, I would recommend setting 8580 Filter Bias to +3000 and engine to resid-33 as a starting point, it's the best emulation of the 8580s in my systems I've heard to date.

### CODE REVIEW

**Comment by AnaLogiC76** [comment]
As promised some details on the code changes and decisions, I recommend looking at the individual commits for easier reading, it can all be squashed for merging.

Makefile: Support for .cpp-files was incomplete but needed to integrate resid-fp without file-renaming. I hope the final one-line-solution is satisfactory.

Also in Makefile: Improved readability for console-output. I always merge this in when building and think it may be helpful for everyone. The Retroarch-Makefiles have another way to achieve this. It's completely optional and removable if not wanted.

Separate core-options for engine and model: It has always been this way in VICE and with more than 2 engines available it now makes sense. Backward-compatibility needs to be decided, is there any method to update values for the core-options without user-interaction? What about core-overrides that do not automatically save?

resid-33: While at first I had a wrapper-class for the Filter-implementations virtualizing the methods and member-accesses, the solution here is much simpler and has no runtime performacne-impact, it is just another array with function-pointers.
Just one more source-file required. It resides in the vice-tree even though it is not part of the original vice-source. I didn't put it in the libretro-tree because it is in no way related to the libretro API. Where should it go?

resid-fp: New subtree in vice-source, and resid-fp.cc to integrate it. Same as above, is there a better place for this?

Core-options for filter-parameters: I actually did those before finding out they had no effect for resid-24 with 8580. For the new resid-engines it's now usefull to have them to do live-changes instead of having to edit vicerc.

The new engines are integrated by modifying files in vice/src/sid - there should be another way to do this, with a wrapper.c-file which includes and compiletime-patches the original files.
What solution is prefered - changing the VICE-source or a wrapper?

New engines available in all cores, even those that currently do not offer SID-support: Those system can use the SID by using a SID-cart, there's currently no core-option to enable that. Maybe that would be desirable one day, so I made the engines available to those cores aswell. Also with the changes in vice/src/sid they would not compile otherwise, with a wrapper (see above) it would be feasable to not have the new engines available for those cores by including the wrapper just for cores offering SID-support right now.

I hopefully covered it all. Ready for questions.

**Comment by AnaLogiC76** [comment]
Rebased. Also four weeks have passed, did anyone have time to look into it?

**Comment by rsn8887** [comment]
Too much wall of text. Can you tell me if I understood this correctly?

It seems that this PR does three things:
- implements resid-33 as optional sid engine
- implements resid-fp as optional sid engine
- allows separate setting of sid model and sid engine in core options


Does this keep the old 2.4 sid engine as default and unchanged from before (the one without farting filters)? So if the user doesn't actively change to resid-33 or resid-fb, the sound stays the same as before if this is merged?

**Comment by rsn8887** [comment]
Doesn't link on Switch. Missing -fPIC flag, probably related to Makefile changes.

**Comment by AnaLogiC76** [comment]
I tried to keep it compact but it was a long way.

You got it right, resid-24 is untouched and still default.
Filter-settings apply to both resid-33 and resid-fp - resid-24 doesn't support this, VICE since at least 2.4 doesn't either.

Regardings defaults, Retroarch offers no facility for config conversion - if it doesn't recognize a value in the config, the default is applied. This means a customized engine/model-configuration needs to be set again. I thought about a method to avoid this, but found none as RA also does not offer any means to programmatically update the config, only the user can do this via the UI.

**Comment by rsn8887** [comment]
Sounds good. Did you check the CXXFlags are actually correct for all patforms? At least for libnx they are wrong.

**Comment by AnaLogiC76** [comment]
I only changed the rule to support .cpp-files - but the compile-rule for them always used CXXFLAGS, so if flags are missing that's where they are missing.

**Comment by rsn8887** [comment]
But this will break compilation for all platforms where CXXFLAGS are not correctly set. Before this didn't matter. So you have to check for each platform that CXXFLAGS are correct. Basically they should be identical to CFLAGS if in doubt, I think.

**Comment by AnaLogiC76** [comment]
I once took a look at how the flags are built back when we had the Makefile-discussion and found there are quite a few places adding flags. So this is not quick to verify.
I can do this, syncing CXXFLAGS to CFLAGS where necessary, but it sure will take a day or two.

**Comment by rsn8887** [comment]
Maybe take a look if you can. I just glanced over Makefile.libretro and it seems it is already done for all (most?) platforms. libnx was the exception it seems.

**Comment by rsn8887** [comment]
Here is the diff to fix compilation on Switch: 
```
diff --git a/Makefile.libretro b/Makefile.libretro
index 5ec2fe92e..1a9514e73 100644
--- a/Makefile.libretro
+++ b/Makefile.libretro
@@ -111,11 +111,13 @@ else ifeq ($(platform), classic_armv8_a35)
 else ifeq ($(platform), libnx)
    include $(DEVKITPRO)/libnx/switch_rules
    TARGET := $(TARGET_NAME)_libretro_$(platform).a
-   CFLAGS += -O3 -fomit-frame-pointer -ffast-math -I$(DEVKITPRO)/libnx/include/ -fPIE -Wl,--allow-multiple-definition
+   CFLAGS += -O3 -fomit-frame-pointer -ffast-math -I$(DEVKITPRO)/libnx/include/ -Wl,--allow-multiple-definition
    CFLAGS += -specs=$(DEVKITPRO)/libnx/switch.specs
    CFLAGS += -D__SWITCH__ -DHAVE_LIBNX -DHAVE_GETPWUID=0 -DHAVE_GETCWD=1
    CFLAGS += -march=armv8-a -mtune=cortex-a57 -mtp=soft -ffast-math -mcpu=cortex-a57+crc+fp+simd -ffunction-sections
    CFLAGS += -Ifrontend/switch -ftree-vectorize
+   CXXFLAGS += $(CFLAGS)
+   fpic = -fPIE
    STATIC_LINKING=1
```

**Comment by rsn8887** [comment]
I just tested this PR on Switch and it works (with my diff above). I think it is great! Hard to tell which of the three choices sounds better resid, resid-33, or resid-fp. But it is great to have the choice.

**Comment by AnaLogiC76** [comment]
Glad you like the new engines, my personal favourite is resid-33 with filter gain set to +3000, emulates my real machines best. Btw the default is -3000 because VICE said so, what do you think, should we keep it that way?

Regarding Makefile and full commandline output, Retroarch itself only outputs filenames, at least with default settings, maybe buildbot passes some parameter to enable more output - there is some non-trivial system in place there, maybe @twinaphex could help here?

Now that switch works, should I still take a look at the CFLAGS vs CXXFLAGS situation?

**Comment by AnaLogiC76** [comment]
I've now with a modified Makefile.libretro and some shell magic created diffs showing how CFLAGS and CXXFLAGS differ per platform - I found 17 platform-strings and hope that covers them all.
Here is the zip with the diffs for anyone interested.
[cflags-diff.zip](https://github.com/libretro/vice-libretro/files/4170441/cflags-diff.zip)

It turned out for some platforms a lot was missing in CXXFLAGS - so I applied merging CFLAGS for 4 affected platforms plus the patch by @rsn8887, that got rid of all differences.

**Comment by sonninnos** [comment]
Since I don't have a healthy relationship with 8580 I don't really mind one way or the another, if these changes only affect 8580. But still it is always nice if stuff work more like they should. Like currently Last Ninja Remix intro tune has no bass with 8580 ReSID (I assume it should have, since it does with FastSID). Haven't tried yet if this fixes it.

But could those RETRORESIDFILTERBIAS and RETRORESID8580FILTERBIAS be combined like the others? Why have them separate, or are they vastly different between the chips, so switching back and forth is a hassle? I would not mind if the filter options are not exposed at all, and instead they would forced to be as accurate as possible. Since we already have an abundance of options.

Also I vote for ditching the VICE default -3000 and keeping the one that feels more accurate.

**Comment by AnaLogiC76** [comment]
There are two tunes with this name, do you mean the one by Reyn Ouwehand? Here's a recording from a real 8580, the baseline is pretty much inaudible there aswell: http://gensho.ftp.acc.umu.se/mirror/media/Oakvalley/soasc/hvsc/049/MP3/MUSICIANS/O/Ouwehand_Reyn/Last_Ninja_Remix_T001.sid_CSG8580R5.mp3
Linked from a page with lots of SID-recording, with search-engine, very usefull: https://www.6581-8580.com/socse/index.php

The problem with accuracy here is that analog components around the 6581 apparently vary a lot and there also are several 6581-revisions with different sound. Supposedly its simpler with the 8580, but the resid-33-default by VICE sounds unusual too me, so maybe it's not.
Btw if you set 8580 filter gain to 0 it sounds quite similar to resid-24 - so I've no idea how they came up with that default-value.
But this means at least being able to set the filter gain is a major point of the additional SID engines.

Here's an example where resid-24 or filter gain 0 sounds better than any higher value - you can extract the HVSC-path from the URL to try the .sid for yourself:
http://ftp.acc.umu.se/mirror/media/Oakvalley/soasc/hvsc/062/MP3/MUSICIANS/B/Blues_Muz/Roestoeen_Kristian/Klogge_T001.sid_CSG8580R5.mp3

**Comment by sonninnos** [comment]
Yes, that one. So FastSID plays it wrong then. I only have a real 6581 to do comparisons with if it helps anything.

But sure, the options can be hidden anyway, so it was pretty pointless nitpicking from my part to not expose them.

**Comment by rsn8887** [comment]
I think it is great as-is. Any objections to merging as-is?

**Comment by AnaLogiC76** [comment]
I'd change filter gain default from VICE default to something sane, at least 0 (sounds similar to resid-24) or a bit below the value I use - maybe middle-ground, 1500?
Those who show audio options will see the settings anyway and play with them.
I'd then remove wip and that would be it from my side.
You've seen the new makefile commit with more flag merging?
https://github.com/libretro/vice-libretro/pull/189/commits/cec02abfdd59cb879842b4d8bc5a89dffefdd63d

**Comment by rsn8887** [comment]
Yes, ok I will wait then until WIP is removed from the title.

**Comment by AnaLogiC76** [comment]
Updated default value, changed commit message accordingly, wip removed.

**Comment by rsn8887** [comment]
Thanks!

**Comment by twinaphex** [comment]
Can we please downgrade this at least to C++98. Having a required C++11 module in a completely C based project is pretty bad from a portability perspective.

**Comment by twinaphex** [comment]
And if you determine you can't downgrade it, I require that a compile time ifdef gets introduced so that it can be completely baked out. We have to do this or else this software's portability will suffer immensely and it can no longer be easily deployed on older platforms where there is no C++11 compiler, or C++11 support is spotty at best.

**Comment by rsn8887** [comment]
Yup this C++ dependence broke compilation on a host of platforms, and it is not as simple as undefining HAVE_CXX11, I tried that.

I had to force-undo this PR because of the above mentioned C++ dependencies.
@AnaLogiC76 Can you re-open a new PR from your AnaLogiC76:sid-engines-resid33-residfp branch and make it WIP again, so we can fix those things?

**Comment by rsn8887** [comment]
Is resid-fp the only part that requires CXX11? Maybe we can just do without that one.

**Comment by rsn8887** [comment]
I tried to revert the addition of resid-fp on my branch https://github.com/rsn8887/vice-libretro/tree/sid-engines-fixed . It seems like that one was the main problem. However,  I still get compilation problems on osx even with resid-fp removed: 
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: warning: OS version (10.1.0) too small, changing to 10.4.0
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vice_x64_libretro.dylib] Error 1
```

**Comment by AnaLogiC76** [comment]
For clarification resid-fp does not require C++11, it just does support it and I enabled it because std::autoptr is deprecated with C++17 which causes lots of warnings with current g++.

I wasn't aware of C++98 being the limit, in that case flags should define that limitation on platforms using current g++. I'll look into that, that should also remove the C++17-warnings with, if not I'll find another solution for that.

If HAVE_CXX11 is removed, everything should work despite those warnings.
What is the status of the mentioned linker error with OSX?

**Comment by rsn8887** [comment]
Testing compilation on osx with the residfp commit: 
- with the `#define HAVE_CXX11`:
```In file included from vice/src/residfp/builders/residfp-builder/residfp/Filter.cpp:23:
./vice/src/residfp/builders/residfp-builder/residfp/Filter.h:99:21: error: use of undeclared identifier 'nullptr'
        currentGain(nullptr),
                    ^
./vice/src/residfp/builders/residfp-builder/residfp/Filter.h:100:22: error: use of undeclared identifier 'nullptr'
        currentMixer(nullptr),
                     ^
./vice/src/residfp/builders/residfp-builder/residfp/Filter.h:101:23: error: use of undeclared identifier 'nullptr'
        currentSummer(nullptr),
                      ^
./vice/src/residfp/builders/residfp-builder/residfp/Filter.h:102:26: error: use of undeclared identifier 'nullptr'
        currentResonance(nullptr),
                         ^
4 errors generated.
make: *** [vice/src/residfp/builders/residfp-builder/residfp/Filter.o] Error 1
```
- without the `#define HAVE_CXX11`:
```
In file included from vice/src/sid/resid-fp.cc:23:
In file included from ./vice/src/residfp/builders/residfp-builder/residfp/SID.h:275:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:645:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:2405:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_03:129:5: error: too many
      template arguments for class template 'auto_ptr'
    unique_ptr<__func, _Dp> __hold(__a.allocate(1), _Dp(__a, 1));
    ^                  ~~~~
./vice/src/residfp/sidcxx11.h:32:22: note: expanded from macro 'unique_ptr'
#  define unique_ptr auto_ptr
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2080:56: note: template is
      declared here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 auto_ptr
                                                       ^
```

I guess residfp just never compiled on osx, and I just mis-remembered testing it. I guess I only tested Switch.

**Comment by AnaLogiC76** [comment]
Thanks for the OSX make-output - I now see C++-libraries are included after something like #define unique_ptr auto_ptr - this is bound to awfully fail somewhere and needs include-reordering - I'll take care of that.
I've already updated Makefile to enforce C++98/C99-compliance and fixed the resulting errors in residfp, basically missing defines.

Regarding compact Makefile-output, I see it has been removed again - was there an issues with it or any statement its not allowed? If so, may it be acceptable to only enable it depending on an environment-variable?
Retroarch-Makefile can do it, so I think there has to be an accepted way.

I'll create a new PR as soon as I've a cleaned-up residfp to show.

**Pull request merged**
