### PR TITLE
Sound-Samplerate: Remove low quality options, Reinitialize output on change

### PR DESCRIPTION
**Pull request by AnaLogiC76**
Update to PR #167, also removing unnecessary code as RA already does data validation for us.

### CODE REVIEW

**Comment by AnaLogiC76** [comment]
Second commit adds runtime change of setting.
While according to log this works fine I have no audio-device available here to verify there are no audible artefacts when switching rate, so I marked this as WIP until tested, should be able to do this later today.

**Comment by AnaLogiC76** [comment]
Verified switching rate works fine, several times in a row too, also had no A/V-sync-issues.
Removing WIP.

**Comment by AnaLogiC76** [comment]
Rebased on master, reminding this isn't merged yet.

**Comment by rsn8887** [comment]
Looks good, merging.

**Pull request merged**
