### PR TITLE
Removed real timing & added disk control

### PR DESCRIPTION
**Pull request by sasq64**
* Removed usage of sleep() and time() from core
* Added disk control functions and "no rom" support so emulation can be started without game
* Some minor cleanup

### CODE REVIEW

**Comment by sasq64** [comment]
I have a feeling there might be discussion about me removing `sleep()` so bring it...

**Comment by sasq64** [comment]
Hmm can anyone tell me what went wrong with the Wii CI test ? Can't tell from the log...

**Comment by twinaphex** [comment]
I think you are right to be removing timing code. Cores should strife to be deterministic instead so you did a good thing there.

**Comment by r-type** [comment]
So what is the purpose to remove gettick() ? i understand removing sleep but not gettick

**Comment by sasq64** [comment]
It makes the core non deterministic -- for instance, for netplay to work you want two cores running the same roms and getting the same events to produce the same results. If we "leak" real world data into the core that is no longer true.

**Pull request merged**
