### PR TITLE
[VITA] Working

### PR DESCRIPTION
**Pull request by frangarcj**
@twinaphex take a look

### CODE REVIEW

**Comment by r-type** [comment]
seriously, add more 363 files just for retro_dirent stuff ? 
can't you just add the minimum needed file to support retrodirent instead of all the libretro common?

**Comment by frangarcj** [comment]
I thought that dir is treated like a package. If not I'll remove unneeded files

**Comment by frangarcj** [comment]
now?

**Comment by twinaphex** [comment]
I will redo the PR to only take the files actually needed. This will prevent git history from mushrooming.

**Comment by twinaphex** [comment]
Can you redo this PR instead @frangarcj ? Sorry for the inconvenience.

**Pull request closed without merging**
