### PR TITLE
WIP: Fix for cartridge from vicerc ignored

### LINKED ISSUE #140: Using cartridges via vicerc no longer work
Thanks @monkeyman79 for the updates, but I stumbled upon a breakage and can't seem to figure out how to it fix easily and not break something else.

I've been attaching an Action Replay cartridge via `vicerc` in system/vice/ like so:

> [C64SC]
CartridgeFile="path"

But it does nothing anymore. I've narrowed it down to two culprits in `retro_run()`:
`resources_set_defaults()` AND `initcmdline_restart()` (specifically `mon_cart_cmd.cartridge_detach_image`)

Perhaps you have the quickest understanding of what needs to be done. Please also wrap the new `initcmdline_restart()` function with `#ifdef __LIBRETRO__` so it will make future source updates a lot less painful. Thanks in advance!

### PR DESCRIPTION
**Pull request by monkeyman79**
Close #140

### CODE REVIEW

**Comment by rsn8887** [comment]
Oops was there something wrong with this? I merged even though it was labeled WIP

**Comment by monkeyman79** [comment]
Too early

**Comment by rsn8887** [comment]
Ok will revert.

**Comment by rsn8887** [comment]
Sorry, can you open a new PR? Thanks.

**Pull request merged**
