### PR TITLE
Remove Nuklear GUI, Add VKBD touch control

### LINKED ISSUE #202: change aspect ratio?
Hi, is there an option to switch between 4:3 (current DAR) and NTSC / PAL based on pixel aspect ratios?
http://hitmen.c02.at/temp/palstuff/

### LINKED ISSUE #213: VSF snapshots saved using WinVICE and GTK3VICE don't load
As per title. Not sure if this is a bug, or a feature not yet implemented. Would be super-useful to have support for this, so we can load snapshots that bypass trainers.

### PR DESCRIPTION
**Pull request by sonninnos**
- Replaced bloaty Nuklear with the lightweight VKBD from PUAE
  - No drawbacks, only benefits: Touch control, better performance, simpler maintenance

**Number proofs (Fastforward FPS x64sc 24bit color):**
| VKBD hidden | VKBD opaque | VKBD transparent | FPS hit (transparent/hidden) | |
|---|---|---|---|---|
|375|222|212|43,5%|**Before**|
|375|365|348|7,2%|**After**|

Bonus:
+ Shortcut for ShiftLock to RetroPad Y while VKBD visible
+ Aspect Ratio core option (Auto, PAL, NTSC, 1:1)
   Closes #202
+ VSF extension added
   Closes #213

+ Cleanups

Like before, please confirm with a real touch device and all zoom settings etc!

### CODE REVIEW

**Comment by rsn8887** [comment]
on x64 (fast) core on Switch using default core options, the horizontal touch scaling seems a bit off: touching Q triggers W, touching W triggers E. R,T,Y,U are almost corrects, and the left side of I triggers U, O triggers I, P triggers O etc.

**Comment by rsn8887** [comment]
Same on x64sc core. F3 is a good example: I have to touch to the right of "F3" to trigger F3. And Q: I have to touch to the left of Q to trigger "Q". Only horizontal is a problem, vertical coords are fine.

**Comment by rsn8887** [comment]
I have to touch in the left red area to trigger "1" and in the right red area to trigger "F1" when borders are ON and zoom OFF

image

**Comment by sonninnos** [comment]
Whoops. Should be sorted now.

**Comment by rsn8887** [comment]
Works perfect on Switch now!

**Comment by rsn8887** [comment]
Merging

**Pull request merged**
