### PR TITLE
VKBD enhancements

### LINKED ISSUE #468: C128 keyboard
Hi,

Emulator works great, the addition of REU was very good for GEOS, thanks !
Just one thing that bugs me, the C128 virtual keyboard is not complete, some of the extra keys (compared to C64) are missing, F5 and F6, for instance, have the same behaviour (HELP) whereas they shouldn't...

Is there any plan to make the keyboard 100% like the original ?

Many thanks and best regards

### PR DESCRIPTION
**Pull request by sonninnos**
VKBD:
- Blended font shadows
- Dimmed surroundings
- Section gap
- Use 4 letters max instead of 3

C128:
- Proper VKBD layout for C128
  Closes #468 
- Fix 40/80 toggle switching

Other:
- TCRT extension to valid list
- Auto-enable TDE with TCRT
- Auto-disable TDE with D2M/D4M

### CODE REVIEW

**Comment by Vweber73** [comment]
Got it, very nice, first time I see a proper C128 emulated keyboard, many thanks !
I see the Amiga core has changed version as well - any changes on the keyboard side as well ?
Many thanks and best regards

**Comment by Vweber73** [comment]
Maybe I misunderstood but I can't get how 40/80 columns works. The only working screen is the one I booted from, depending on the system options Vic/vdc setting. The other one is black screen, no matter how I play with the 40/80 key or Vic/Vdc setting. Am I missing something ?

**Comment by sonninnos** [comment]
But that is how it works. It depends on the software and the startup which is being actually outputted to, and there can be only one at a time.

**Comment by sonninnos** [comment]
Yes the core option is the initial startup state of that button, and the button overrides that. Maybe the VKBD key should be a similar toggle-key as ShitLock is, since I found this explanation:

> The 40/80 DISPLAY key is another mechanically latched button. It determines the display mode on power up or when the reset hutton is depressed. Latching it down defaults to the 80 column display. It has no effect once the computer is up and running.

So logically VICE uses the same key to switch the output (since 40/80 modes are physically via different outputs/monitors) even though it shouldn't actually do anything while running.

**Comment by Vweber73** [comment]
Thanks, I understand now, the button is not (yet) a latch one, that's why I got results I felt were inconsistant, since I expected the "latch" behaviour. Yes indeed I think it should be the same as shift+lock :)
Btw is there a dedicated reset button somewhere like on the real C128, or do I have to use RA "restart" (with the option of hard, soft, and other reset types) ?
Also, in zoom mode, the status bar overrides the bottom part of the C128 screen, could it be below it ? Or RA constraints leaves no choice ?
Best regards

**Comment by sonninnos** [comment]
The menu "Restart" does hardreset+autostart, as in it does not care about the core option. Core option reset type matters when using the hotkey (default End) or VKBD key.

And of course the statusbar has to be inside the screen. Use smaller zooming then if it is in the way.

**Comment by Vweber73** [comment]
Ok, thanks. Is there a VKBD key for reset ? Could't find it... the one next to the tape deck doesn't seem to work...

So it is ok for your to make the 40/80 key a "latch" one in an upcoming version ? 

Cheers

**Comment by sonninnos** [comment]
The VKBD reset key needs to be held down for a while, to prevent accidental touch screen presses.

And yes I'll look into it.

**Comment by Vweber73** [comment]
Ah yes, I see it.
Many thanks !

**Comment by Vweber73** [comment]
Pressing the rectangle to hide the VKBD triggers "Monitor"... quite ennoying, just like for PUAE, Retroarch controls interferes with the emulated machine controls. 
PUAE and VICE are by far the best and most complete Commodore emulators for Android, but RetroArch constraints makes them more difficult to use than it should be. What is ok for game consoles is not adapted to computers. My dream would be to have these emulators nativelyw without those UI constraints, and especially with the possibility to have the (otherwise very good) VKBD below the emulated machine's screen, not over it with transparency. On my Samsung Z fold 3 this would be ideal use od the real estate...

**Pull request merged**
